### ISSUE TITLE
Reflector missing import { _Math } from '../math/Math'

### ISSUE THREAD

**Issue by invention7** [Itee/threejs-full-es6#11] opened 2018-02-10 05:09 UTC
Love this project.

Reflector.js throws an error missing Math.isPowerOfTwo.
To fix, Reflector.js needs
    import { _Math } from '../math/Math'

and line 65 needs to be updated with the underscore.
if ( ! _Math.isPowerOfTwo( textureWidth ) || ! _Math.isPowerOfTwo( textureHeight ) ) {

**Comment by Itee** [comment] 2018-02-14 17:36
Thank for the feed back !

This is a duplicate of #8. 

It will be fixed in the next major release that come this night !

Best regards

**Closed as completed by Itee** 2018-02-14 17:36 UTC
Labels: duplicate
